# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws-linux-vm" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws-rdp-visual-studio" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/aws-spot" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/azure-linux" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-code-server-fish" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-code-server" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-gateway-ide" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-gateway-lang" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-in-docker/docker-network-mode-host" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-in-docker/docker-with-docker-network" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-in-docker/sysbox" # Location of package manifests
    schedule:
      interval: "daily"
  
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-jupyter-path" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-kasm-insomnia" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-proxy" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-vnc-eclipse" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-with-jupyter" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/docker-with-vnc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/gcp-rdp-visual-studio" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/gcp-ubuntu-docker" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/k8s-multi-container" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/openshift/intellij-web" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/openshift/pod-kasm-intellij" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/openshift/pod-with-code-server" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/openshift/pod-idea" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/openshift/pod-with-jupyter" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-gateway-ide" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-gateway-lang" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-go" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-idea-vnc" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-idea" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-kasm-intellij" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-node" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-parameter" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-pycharm" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-rstudio" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-code-server" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-docker/kubernetes-tf-provider" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-docker/pod-side-car-pgadmin" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-docker/pod-with-side-car" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-eclipse" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-guacamole" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-jupyter-path" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-jupyter" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-kasm" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-php" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-ruby" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-rust" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/pod-with-vnc" # Location of package manifests
    schedule:
      interval: "daily"
  
  


